package com.application;

public enum RSHDCacheIndices {

    Animations,
    Skeletons,
    Configurations,
    Interfaces,
    Sound_Effects,
    Maps,
    Music_Tracks,
    Models,
    Sprites,
    Textures,
    Binary,
    Music_Jingles,
    Client_Scripts,
    Fonts,
    Vorbis_Samples,
    SoundBank_Patches,
    Location_Objects,
    Enums,
    NPCs,
    Object_Items,
    Spot_Animations,
    Sequences,
    Var_bits,
    World_Map,
    Quick_Chat,
    Quick_Chat_Global,
    Texture_Definitions,
    Particles,
    Defaults,
    Billboards,
    DLLs,
    Shaders,
    Loading_Sprites,
    Loading_Screens,
    Loading_Sprites_Raw,
    Cutscenes,
    Empty_36,
    GFX_Configurations,
    Empty_38,
    Empty_39
}
